services:
  lb:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # Mount the single config file directly:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # (optional) if you have extra conf snippets, mount that dir too; otherwise remove this line:
      # - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web

  web:
    image: nginx:alpine
    expose:
      - "80"

  redis:
    image: redis:alpine
